### ISSUE TITLE
Cookie managment

### ISSUE THREAD

**Issue by gwen001** [UnkL4b/GitMiner#10]
Great tool!

However I had to apply the following patch to make it work:
```
59c59
<         self.cookie = {'user_session':self.args.cookie}
---
>         self.cookie = dict(cookies_are=self.args.cookie)
```

Best regards,

Gwen

**Comment by danilovazb** [comment]
Tks bro!

Done!

**Comment by pvn-hung-tran** [comment]
Does this tool still work? I've tried on my PC but it returns nothing at the moment.

**Comment by gwen001** [comment]
Sure it does!
