### ISSUE TITLE
Please HELP me to find some results in this programm! I will pay 25Euro if someone can help me!

### ISSUE THREAD

**Issue by MatthiasMaltes** [UnkL4b/GitMiner#21]
Hey, I'm writing my Bachelor Thesis about "finding similarities in code from GitHub" . For this Bachelor Thesis I need a lot of code. Now I saw that your tool could help me to find a lot of code but all searches I try to type into your GitMiner Program didn't find any results. These are the searches I've typed in: 
python git_miner.py -q 'extension:h #pragma omp in:file' -o result.txt 

python git_miner.py -q 'extension:hpp #pragma omp in:file' -o result.txt 

python git_miner.py -q 'extension:c #pragma omp in:file' -o result.txt

python git_miner.py -q 'extension:cpp #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:* extension:h #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:* extension:hpp #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:* extension:c #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:* extension:cpp #pragma omp in:file ' -o result.txt
python git_miner.py -q 'filename:test extension:h #pragma omp in:file ' -o result.txt

In his Program he's using the coockie from his own Github account, where can I find it?
Please help me than otherwise I have to open every github page and copy the code and download it. 

Kind regards 

Matthias Maltes﻿

**Comment by danilovazb** [comment]
I'm going to release a 2.0 version at the most in 1 month

**Comment by danilovazb** [comment]
It has been fixed in version 2.0.

Github has changed the way presented the search results, I had to redo the crawler.
