### ISSUE TITLE
Error in example Query: IndexError: list out of range

### ISSUE THREAD

**Issue by expworm** [UnkL4b/GitMiner#8]
root@localhost:~/GitMiner# python git_miner.py --query 'filename:configuration extension:php "public password" in:file' -m joomla

 ██████╗ ██╗████████╗███╗   ███╗██╗███╗   ██╗███████╗██████╗
██╔════╝ ██║╚══██╔══╝████╗ ████║██║████╗  ██║██╔════╝██╔══██╗
██║  ███╗██║   ██║   ██╔████╔██║██║██╔██╗ ██║█████╗  ██████╔╝
██║   ██║██║   ██║   ██║╚██╔╝██║██║██║╚██╗██║██╔══╝  ██╔══██╗
╚██████╔╝██║   ██║   ██║ ╚═╝ ██║██║██║ ╚████║███████╗██║  ██║
 ╚═════╝ ╚═╝   ╚═╝   ╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ v1.1
 Automatic search for GitHub.

 + Autor: Danilo Vaz a.k.a. UNK
 + Blog: http://unk-br.blogspot.com
 + Github: http://github.com/danilovazb
 + Gr33tz: l33t0s, RTFM

 +[WARNING]------------------------------------------+
 | DEVELOPERS ASSUME NO LIABILITY AND ARE NOT        |
 | RESPONSIBLE FOR ANY MISUSE OR DAMAGE CAUSED BY    |
 | THIS PROGRAM                                      |
 +---------------------------------------------------+

+[PAGE: 1/100]-----------------------------------------+
| [USER]: @monghimng
| [LINK]: http://github.com/monghimng/cmc/raw/d9a332d2cc22fc0b17ec9e93f8e5b917be382c83/configuration.php
Traceback (most recent call last):
  File "git_miner.py", line 226, in <module>
    GitMiner().start()
  File "git_miner.py", line 223, in start
    self.parseSearch(HTML.content)
  File "git_miner.py", line 179, in parseSearch
    print("| [" + frescurinha.OKBLUE + "LAST INDEXED" + frescurinha.ENDC + "]: %s" % last_indexed[number_link])
IndexError: list index out of range

**Comment by monghimng** [comment]
May i ask what this is?

**Comment by expworm** [comment]
An error executing an example query

**Comment by monghimng** [comment]
oh i get it now, so the guy developed a git miner, and it didn't work, so you are filing a ticket, right? just wondering cuz i never understand how github works

**Comment by monghimng** [comment]
this is so cool, how did you find this program?

**Comment by 5up3rc** [comment]
Traceback (most recent call last):
  File "git_miner.py", line 226, in <module>
    GitMiner().start()
  File "git_miner.py", line 223, in start
    self.parseSearch(HTML.content)
  File "git_miner.py", line 179, in parseSearch
    print("| [" + frescurinha.OKBLUE + "LAST INDEXED" + frescurinha.ENDC + "]: %s" % last_indexed[number_link])
IndexError: list index out of range

**Comment by a4m** [comment]
i have the same problem

**Comment by unk-br** [comment]
Made a fix on line 179.

I added a TRY to bypass the indexing error.

Could confirm that it is OK?

**Comment by geolado** [comment]
That's not a fix , its a gambiarra


Em 1 de mai de 2016 13:13 -0300, Danilo Vaz<notifications@github.com>, escreveu:

**Comment by danilovazb** [comment]
@geolado você mita! kkkk
