### ISSUE TITLE
Blank output

### ISSUE THREAD

**Issue by unixfox** [UnkL4b/GitMiner#9]
I ran GitMiner and it outputs nothing, just a small message with every example (in the Readme):

```
 + Autor: Danilo Vaz a.k.a. UNK
 + Blog: http://unk-br.blogspot.com
 + Github: http://github.com/danilovazb
 + Gr33tz: l33t0s, RTFM

 +[WARNING]------------------------------------------+
 | DEVELOPERS ASSUME NO LIABILITY AND ARE NOT        |
 | RESPONSIBLE FOR ANY MISUSE OR DAMAGE CAUSED BY    |
 | THIS PROGRAM                                      |
 +---------------------------------------------------+


+[PAGE: 1/1]-----------------------------------------+
```

I don't know why it worked last month and today it doesn't work.
Maybe Github made some changes on his search page.

**Comment by danilovazb** [comment]
Yes, github made changes in their research, I'm working on it.

**Comment by unixfox** [comment]
@danilovazb Any updates ?

**Comment by unixfox** [comment]
Sorry for asking again but do you have any updates on your work ?

**Comment by danilovazb** [comment]
@unixfox Yes, the weekend do update

**Comment by unixfox** [comment]
@danilovazb Do you have some issues to make it works ?

**Comment by unixfox** [comment]
🆙

**Comment by unixfox** [comment]
@danilovazb ?

**Comment by unixfox** [comment]
I found that Github doesn't allow search code anonymously.
Github search code requires to be authenticated with an account.

**Comment by unixfox** [comment]
@danilovazb 

I tried to pass the `cookies` arg to the requests module with my cookie and it's working great!

Here is my patch (quick dirty fix):

````
From b71561020b1bd55a2e71d1f96c80e77b27b935da Mon Sep 17 00:00:00 2001
From: Emilien Devos <contact@emiliendevos.be>
Date: Sun, 11 Dec 2016 14:40:40 +0100
Subject: [PATCH] fix

---
 git_miner.py | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/git_miner.py b/git_miner.py
index 986963b..6928ef9 100644
--- a/git_miner.py
+++ b/git_miner.py
@@ -53,6 +53,7 @@ class GitMiner(object):
         self.url = "http://github.com"
         self.user_agent = {"User-Agent":"Mozilla/5.0 (X11; Linux x86_64)\
             AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"}
+        self.cookie = dict(user_session='CHANGEME')
         self.args = parser.parse_args()
         if self.args.query is None:
             os.system('cls' if os.name == 'nt' else 'clear')
@@ -128,7 +129,7 @@ class GitMiner(object):
                 print(frescurinha.HELP + "+----------------------------------------------------+"+ frescurinha.ENDC)
                 self.saveOutput("+----------------------------------------------------+\n")
 
-            if self.config[self.args.module]['parameters'] >= 1:
+            if len(self.config[self.args.module]['parameters']) >= 1:
                 qtd_param = int(len(self.config[self.args.module]['parameters']))
                 qtd_order = int(len(self.config[self.args.module]['splitorder']))
                 split_param = self.config[self.args.module]['splitparam']
@@ -200,7 +201,7 @@ class GitMiner(object):
         self.nextPage(prox_page)
 
     def accessWeb(self,url_acesso):
-        acc = requests.get(url_acesso, headers=self.user_agent)
+        acc = requests.get(url_acesso, headers=self.user_agent, cookies=self.cookie)
         if " find any code matching" in acc.text:
             print(frescurinha.FAIL + "[-] We couldn't find any code matching %s\n" % self.args.query + frescurinha.ENDC)
             exit()
-- 
2.10.2
````

**Comment by danilovazb** [comment]
i l0v3 y0u bro!

I'm out of time, my dad passed away recently, I'll do the update!

TKSSS

**Comment by Sceat** [comment]
$Ø $ÂÐ ŦĦØ

**Comment by Robvred** [comment]
Sorry for asking but I'm not shure, do you have update your work with @unixfox change ?

**Comment by unixfox** [comment]
@Robvred If you want to try my patch, here is how to do it:
1. Get the value of the cookie `user_session` for the domain `github.com` and copy it. You can use [`Advanced Cookie Manager`](https://addons.mozilla.org/en/firefox/addon/cookie-manager/) for Firefox for example.
2. Download [my patch](https://gist.github.com/unixfox/1f9def49bd97c099d2cb39e91c8d10da/raw/6d441498c84328a6ba78a25476158009526e0550/gitminer.patch) on the root of the `Gitminer` repository.
3. Edit the patch file and replace `CHANGEME` (at the 18th line) with the value of the cookie `user_session`.
3. Open a terminal and navigate to the `Gitminer` repository.
4. Execute this command:
```
git am --signoff -k < gitminer.patch
```
5. Now Gitminer'll work perfectly.

**Comment by Robvred** [comment]
@unixfox Thanks, all it's fine 👍 Why you don't push on master or secondary branch of project ? it's very useful !

**Comment by danilovazb** [comment]
GitMiner updated!
Add set cookie
Reformulated crawler for new github interface.
